<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Commands\CreateOrderCommand.cs" />
    <Compile Remove="Models\OrderItemModel.cs" />
    <Compile Remove="Models\OrderModel.cs" />
    <Compile Remove="Models\ProductModel.cs" />
    <Compile Remove="Models\ProductOptionModel.cs" />
    <Compile Remove="Models\ProductOptionSelectionModel.cs" />
    <Compile Remove="Queries\OrdersByUserQuery.cs" />
    <Compile Remove="Queries\ProductOptionByIdQuery.cs" />
    <Compile Remove="Queries\ProductOptionsByProductQuery.cs" />
    <Compile Remove="Queries\ProductOptionSelectionQuery.cs" />
    <Compile Remove="Queries\ProductOptionsQuery.cs" />
    <Compile Remove="Queries\ProductsByCategoryQuery.cs" />
    <Compile Remove="Queries\ProductsQuery.cs" />
    <Compile Remove="Store\ProductOptionRepository.cs" />
    <Compile Remove="Store\ProductOptionSelectionRepository.cs" />
    <Compile Remove="Store\ProductRepository.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR.Contracts" Version="2.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\Card\Commands\" />
    <Folder Include="Features\Card\Store\" />
    <Folder Include="Features\Card\Queries\" />
    <Folder Include="Features\Cart\Commands\" />
    <Folder Include="Features\Cart\Queries\" />
    <Folder Include="Features\Cart\Store\" />
    <Folder Include="Features\Delivery\Commands\" />
    <Folder Include="Features\Delivery\Queries\" />
    <Folder Include="Features\Delivery\Store\" />
    <Folder Include="Features\Inventory\Commands\" />
    <Folder Include="Features\Inventory\Queries\" />
    <Folder Include="Features\Inventory\Store\" />
    <Folder Include="Features\Product\Types\Virtual\Commands\" />
    <Folder Include="Features\Product\Types\Virtual\Queries\" />
    <Folder Include="Features\Product\Types\Virtual\Store\" />
    <Folder Include="Features\Review\Commands\" />
    <Folder Include="Features\Review\Queries\" />
    <Folder Include="Features\Review\Store\" />
    <Folder Include="Features\ShippingAddress\Commands\" />
    <Folder Include="Features\ShippingAddress\Queries\" />
    <Folder Include="Features\ShippingAddress\Store\" />
    <Folder Include="Features\Tax\Commands\" />
    <Folder Include="Features\Tax\Queries\" />
    <Folder Include="Features\Tax\Store\" />
    <Folder Include="Features\Wish\Commands\" />
    <Folder Include="Features\Wish\Queries\" />
    <Folder Include="Features\Wish\Store\" />
  </ItemGroup>

</Project>
