<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR.Contracts" Version="2.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Features\Card\Commands\" />
    <Folder Include="Features\Card\Queries\" />
    <Folder Include="Features\Cart\Commands\" />
    <Folder Include="Features\Cart\Queries\" />
    <Folder Include="Features\Delivery\Commands\" />
    <Folder Include="Features\Delivery\Queries\" />
    <Folder Include="Features\Inventory\Commands\" />
    <Folder Include="Features\Inventory\Queries\" />
    <Folder Include="Features\Product\Commands\" />
    <Folder Include="Features\Product\Queries\" />
    <Folder Include="Features\Review\Commands\" />
    <Folder Include="Features\Review\Queries\" />
    <Folder Include="Features\ShippingAddress\Commands\" />
    <Folder Include="Features\ShippingAddress\Queries\" />
    <Folder Include="Features\Vat\Commands\" />
    <Folder Include="Features\Vat\Queries\" />
    <Folder Include="Features\Wish\Commands\" />
    <Folder Include="Features\Wish\Queries\" />
  </ItemGroup>

</Project>
