<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Features\User.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Hat.Domain\Hat.Domain.csproj" />
  </ItemGroup>

</Project>
