<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Http" Version="2.3.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="8.0.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Hat.Infrastructure.Identity.Memory\Hat.Infrastructure.Identity.Memory.csproj" />
    <ProjectReference Include="..\Hat.Infrastructure.Payment.Fake\Hat.Infrastructure.Payment.Fake.csproj" />
    <ProjectReference Include="..\Hat.Infrastructure.Persistance.SqlServer\Hat.Infrastructure.Persistance.SqlServer.csproj" />
  </ItemGroup>

</Project>
